/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AlunosController;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Emy
 */
public class CadastroAlunos extends javax.swing.JFrame {
    
    private final AlunosController controller;

    /**
     * Creates new form CadastroAlunos
     */
    public CadastroAlunos() {
        initComponents();
        controller = new AlunosController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFitPlus = new javax.swing.JLabel();
        jLabelTxtCadAluno = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelDataNasc = new javax.swing.JLabel();
        jTextFieldDataNasc = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTel = new javax.swing.JLabel();
        jTextFieldTel = new javax.swing.JTextField();
        jLabelPlano = new javax.swing.JLabel();
        jComboBoxPlano = new javax.swing.JComboBox();
        jLabelDtaInicio = new javax.swing.JLabel();
        jTextFieldDtaInicio = new javax.swing.JTextField();
        jButtonCadAluno = new javax.swing.JButton();
        jButtonPgInicial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFitPlus.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelFitPlus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFitPlus.setText("FIT PLUS");
        getContentPane().add(jLabelFitPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabelTxtCadAluno.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelTxtCadAluno.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTxtCadAluno.setText("Cadastro de Alunos");
        getContentPane().add(jLabelTxtCadAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setText("Nome Completo");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 420, 30));

        jLabelDataNasc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelDataNasc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDataNasc.setText("Data de Nascimento");
        getContentPane().add(jLabelDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextFieldDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataNascActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 420, 30));

        jLabelCPF.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCPF.setText("CPF");
        getContentPane().add(jLabelCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        getContentPane().add(jTextFieldCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 420, 30));

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 420, 30));

        jLabelTel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTel.setText("Telefone");
        getContentPane().add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jTextFieldTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 420, 30));

        jLabelPlano.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelPlano.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlano.setText("Plano");
        getContentPane().add(jLabelPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jComboBoxPlano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecionar um Plano", "Plano 1 - Diária", "Plano 2 - Semanal", "Plano 3 - Mensal", "Plano 4 - Semestral", "Plano 5 - Anual" }));
        jComboBoxPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlanoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 420, 30));

        jLabelDtaInicio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelDtaInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDtaInicio.setText("Data de Início");
        getContentPane().add(jLabelDtaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));
        getContentPane().add(jTextFieldDtaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 420, 30));

        jButtonCadAluno.setBackground(new java.awt.Color(255, 102, 51));
        jButtonCadAluno.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonCadAluno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadAluno.setText("Cadastrar");
        jButtonCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 280, 40));

        jButtonPgInicial.setBackground(new java.awt.Color(255, 102, 51));
        jButtonPgInicial.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonPgInicial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPgInicial.setText("Voltar");
        jButtonPgInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPgInicialActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPgInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 560, 280, 40));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLANOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 120, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1 - Diária            R$ 35         x1 ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2 - Semanal       R$ 50         x1 ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3 - Mensal          R$ 120       x1 ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("4 - Semestral     R$ 110       x6 ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5 - Anual             R$ 85         x12");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 410, 330));

        jLabelFundo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelFundo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telaPrincipal1.PNG"))); // NOI18N
        jLabelFundo.setAlignmentY(0.0F);
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 638));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataNascActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelActionPerformed

    private void jComboBoxPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlanoActionPerformed

    private void jButtonPgInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPgInicialActionPerformed
        // TODO add your handling code here:
        MenuPrincipal telamenu = new MenuPrincipal();
        telamenu.setVisible(true);
    }//GEN-LAST:event_jButtonPgInicialActionPerformed

    private void jButtonCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadAlunoActionPerformed
        // TODO add your handling code here:
        controller.salvaAluno();
    }//GEN-LAST:event_jButtonCadAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlunos().setVisible(true);
            }
        });
    }

    public JComboBox getjComboBoxPlano() {
        return jComboBoxPlano;
    }

    public void setjComboBoxPlano(JComboBox jComboBoxPlano) {
        this.jComboBoxPlano = jComboBoxPlano;
    }

    public JTextField getjTextFieldCPF() {
        return jTextFieldCPF;
    }

    public void setjTextFieldCPF(JTextField jTextFieldCPF) {
        this.jTextFieldCPF = jTextFieldCPF;
    }

    public JTextField getjTextFieldDataNasc() {
        return jTextFieldDataNasc;
    }

    public void setjTextFieldDataNasc(JTextField jTextFieldDataNasc) {
        this.jTextFieldDataNasc = jTextFieldDataNasc;
    }

    public JTextField getjTextFieldDtaInicio() {
        return jTextFieldDtaInicio;
    }

    public void setjTextFieldDtaInicio(JTextField jTextFieldDtaInicio) {
        this.jTextFieldDtaInicio = jTextFieldDtaInicio;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldNome() {
        return jTextFieldNome;
    }

    public void setjTextFieldNome(JTextField jTextFieldNome) {
        this.jTextFieldNome = jTextFieldNome;
    }

    public JTextField getjTextFieldTel() {
        return jTextFieldTel;
    }

    public void setjTextFieldTel(JTextField jTextFieldTel) {
        this.jTextFieldTel = jTextFieldTel;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadAluno;
    private javax.swing.JButton jButtonPgInicial;
    private javax.swing.JComboBox jComboBoxPlano;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelDtaInicio;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFitPlus;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPlano;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelTxtCadAluno;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldDataNasc;
    private javax.swing.JTextField jTextFieldDtaInicio;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables
}
