/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.UsuarioController;
import Models.Usuario;
import dao.Conexao;
import dao.UsuarioDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Emy
 */
public class CadastroUser extends javax.swing.JFrame {
    private final UsuarioController controller;

    /**
     * Creates new form CadastroAlunos
     */
    public CadastroUser() {
        initComponents();
        controller = new UsuarioController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFitPlus = new javax.swing.JLabel();
        jLabelCadUser = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFielUser = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonCadTreinador = new javax.swing.JButton();
        jButtonPgInicial = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFitPlus.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelFitPlus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFitPlus.setText("FIT PLUS");
        getContentPane().add(jLabelFitPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabelCadUser.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelCadUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadUser.setText("Cadastro de Usuários");
        getContentPane().add(jLabelCadUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelUser.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("Usuário");
        getContentPane().add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jTextFielUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 420, 30));

        jLabelSenha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 420, 30));

        jButtonCadTreinador.setBackground(new java.awt.Color(255, 102, 0));
        jButtonCadTreinador.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonCadTreinador.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadTreinador.setText("Cadastrar");
        jButtonCadTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadTreinadorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadTreinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 420, 40));

        jButtonPgInicial.setBackground(new java.awt.Color(255, 102, 51));
        jButtonPgInicial.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonPgInicial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPgInicial.setText("Voltar");
        jButtonPgInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPgInicialActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPgInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 420, 40));

        jLabelFundo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelFundo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telaPrincipal1.PNG"))); // NOI18N
        jLabelFundo.setAlignmentY(0.0F);
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 638));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielUserActionPerformed

    private void jButtonPgInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPgInicialActionPerformed
        // TODO add your handling code here:
        MenuPrincipal telamenu = new MenuPrincipal();
        telamenu.setVisible(true);
    }//GEN-LAST:event_jButtonPgInicialActionPerformed

    private void jButtonCadTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadTreinadorActionPerformed
          controller.salvaUsuario();
    }//GEN-LAST:event_jButtonCadTreinadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUser().setVisible(true);
            }
        });
    }

    public JPasswordField getjPasswordFieldSenha() {
        return jPasswordFieldSenha;
    }

    public void setjPasswordFieldSenha(JPasswordField jPasswordFieldSenha) {
        this.jPasswordFieldSenha = jPasswordFieldSenha;
    }

    public JTextField getjTextFielUser() {
        return jTextFielUser;
    }

    public void setjTextFielUser(JTextField jTextFielUser) {
        this.jTextFielUser = jTextFielUser;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadTreinador;
    private javax.swing.JButton jButtonPgInicial;
    private javax.swing.JLabel jLabelCadUser;
    private javax.swing.JLabel jLabelFitPlus;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFielUser;
    // End of variables declaration//GEN-END:variables
}
