/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.TreinadorController;
import Models.Treinador;
import dao.Conexao;
import dao.TreinadorDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emy
 */
public class TreinadoresCadastrados extends javax.swing.JFrame {

    private final TreinadorController controller;

    /**
     * Creates new form MenuPrincipal
     */
    public TreinadoresCadastrados() {
        initComponents();
        controller = new TreinadorController(this);
        mostrarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFitPlus = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonPgInicial = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTreinadores = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1122, 638));
        setMinimumSize(new java.awt.Dimension(1122, 638));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFitPlus.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelFitPlus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFitPlus.setText("FIT PLUS");
        getContentPane().add(jLabelFitPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("Treinadores Cadastrados");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButtonPgInicial.setBackground(new java.awt.Color(255, 102, 51));
        jButtonPgInicial.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonPgInicial.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPgInicial.setText("Voltar");
        jButtonPgInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPgInicialActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPgInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 200, 40));

        jTableTreinadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Completo", "Data de Nascimento", "CPF", "E-mail", "Telefone", "Especialidade"
            }
        ));
        jScrollPane1.setViewportView(jTableTreinadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 800, 540));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 530, 200, 40));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telaPrincipal1.PNG"))); // NOI18N
        jLabelFundo.setAlignmentY(0.0F);
        jLabelFundo.setAutoscrolls(true);
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1122, 638));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPgInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPgInicialActionPerformed
        // TODO add your handling code here:
        MenuPrincipal telamenu = new MenuPrincipal();
        telamenu.setVisible(true);
    }//GEN-LAST:event_jButtonPgInicialActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:

        try {
            Connection conexao = new Conexao().getConnection();
            TreinadorDAO treinadordao = new TreinadorDAO(conexao);
            Treinador treinador = new Treinador();
            
            int index = jTableTreinadores.getSelectedRow();
            
            treinador = treinadordao.listar().get(index);
            
            treinadordao.remover(treinador);
            
            mostrarLista();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(TreinadoresCadastrados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreinadoresCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreinadoresCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreinadoresCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreinadoresCadastrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreinadoresCadastrados().setVisible(true);
            }
        });
    }

    public void mostrarLista() {

        DefaultTableModel modelo = (DefaultTableModel) jTableTreinadores.getModel();
        modelo.setNumRows(0);

        jTableTreinadores.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTableTreinadores.getColumnModel().getColumn(1).setPreferredWidth(20);
        jTableTreinadores.getColumnModel().getColumn(2).setPreferredWidth(20);
        jTableTreinadores.getColumnModel().getColumn(3).setPreferredWidth(20);
        jTableTreinadores.getColumnModel().getColumn(4).setPreferredWidth(20);
        jTableTreinadores.getColumnModel().getColumn(5).setPreferredWidth(20);
        
        try {
            
            Connection conexao = new Conexao().getConnection();
            TreinadorDAO treinadordao = new TreinadorDAO(conexao);
            
            for(Treinador t : treinadordao.listar()){
                
                modelo.addRow(new Object[] {
                
                t.getNomeTreinador(),
                t.getDataNascimentoTreinador(),
                t.getCpfTreinador(),
                t.getEmailTreinador(),
                t.getTelefoneTreinador(),
                t.getEspecialidadeTreinador()
                
                });
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(TreinadoresCadastrados.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPgInicial;
    private javax.swing.JLabel jLabelFitPlus;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTreinadores;
    // End of variables declaration//GEN-END:variables
}
